name: build from zip

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: Extract and Fix Path
        run: |
          apt-get update && apt-get install -y unzip
          # استخراج فایل زیپ در یک پوشه موقت
          unzip project.zip -d temp_folder
          
          # بررسی اینکه آیا فایل‌ها داخل یک پوشه داخلی قرار دارند یا مستقیم
          if [ -d "temp_folder/gradle" ]; then
            cp -r temp_folder/* ./
          else
            # پیدا کردن پوشه داخلی و انتقال محتویات به ریشه
            DIR=$(ls temp_folder | head -n 1)
            cp -r temp_folder/$DIR/* ./
          fi

      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Setup Headless Display (Xvfb)
        run: |
          sudo apt-get install -y xvfb

      - name: build with virtual display
        run: xvfb-run --auto-servernum ./gradlew build

      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: build/libs/
